name: build

on:
  push:
    # Trigger this workflow only on commits pushed to the main branch
    branches:
      - main

jobs:
  dagger:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      # You need to run `dagger project init` locally before and commit the cue.mod directory to the repository with its contents
      - name: Dagger build
        uses: dagger/dagger-for-github@v2
        # See all options at https://github.com/dagger/dagger-for-github
        with:
          version: 0.2
          # To pin external dependencies, you can use `project update github.com/[package-source]@v[n]`
          cmds: |
            project update
            do build
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            build